use Sociodemografico
go

-- Dar de alta los registros que van en la entidad: 'Estado'

INSERT INTO Estado VALUES ('Aguascalientes')
INSERT INTO Estado VALUES ('Baja California')
INSERT INTO Estado VALUES ('Baja California Sur')
INSERT INTO Estado VALUES ('Campeche')
INSERT INTO Estado VALUES ('Chiapas')
INSERT INTO Estado VALUES ('Chihuahua')
INSERT INTO Estado VALUES ('Coahuila de Zaragoza')
INSERT INTO Estado VALUES ('Colima')
INSERT INTO Estado VALUES ('Distrito Federal')
INSERT INTO Estado VALUES ('Durango')
INSERT INTO Estado VALUES ('Guanajuato')
INSERT INTO Estado VALUES ('Guerrero')
INSERT INTO Estado VALUES ('Hidalgo')
INSERT INTO Estado VALUES ('Jalisco')
INSERT INTO Estado VALUES ('Michoacán de Ocampo')
INSERT INTO Estado VALUES ('Morelos')
INSERT INTO Estado VALUES ('México')
INSERT INTO Estado VALUES ('Nayarit')
INSERT INTO Estado VALUES ('Nuevo León')
INSERT INTO Estado VALUES ('Oaxaca')
INSERT INTO Estado VALUES ('Puebla')
INSERT INTO Estado VALUES ('Querétaro')
INSERT INTO Estado VALUES ('Quintana Roo')
INSERT INTO Estado VALUES ('San Luis Potosí')
INSERT INTO Estado VALUES ('Sinaloa')
INSERT INTO Estado VALUES ('Sonora')
INSERT INTO Estado VALUES ('Tabasco')
INSERT INTO Estado VALUES ('Tamaulipas')
INSERT INTO Estado VALUES ('Tlaxcala')
INSERT INTO Estado VALUES ('Veracruz de Ignacio de la Llave')
INSERT INTO Estado VALUES ('Yucatán')
INSERT INTO Estado VALUES ('Zacatecas')


-- Dar de alta los registros que van en la entidad: 'Cancer'

INSERT INTO Cancer VALUES ('Bladder')
INSERT INTO Cancer VALUES ('Bone')
INSERT INTO Cancer VALUES ('Brain')
INSERT INTO Cancer VALUES ('Breast')
INSERT INTO Cancer VALUES ('Cervix Uteri')
INSERT INTO Cancer VALUES ('Colon and Rectum')
INSERT INTO Cancer VALUES ('Esophagus')
INSERT INTO Cancer VALUES ('Eyes')
INSERT INTO Cancer VALUES ('Female Genitals')
INSERT INTO Cancer VALUES ('Gallbladder')
INSERT INTO Cancer VALUES ('Heart')
INSERT INTO Cancer VALUES ('Hodgkin''s Lymphoma')
INSERT INTO Cancer VALUES ('Kidney')
INSERT INTO Cancer VALUES ('Larynx')
INSERT INTO Cancer VALUES ('Leukemia')
INSERT INTO Cancer VALUES ('Liver ')
INSERT INTO Cancer VALUES ('Lungs')
INSERT INTO Cancer VALUES ('Lymphoma')
INSERT INTO Cancer VALUES ('Male Genitales')
INSERT INTO Cancer VALUES ('Melanoma')
INSERT INTO Cancer VALUES ('Mesothelioma')
INSERT INTO Cancer VALUES ('Mylenoma')
INSERT INTO Cancer VALUES ('Nervous')
INSERT INTO Cancer VALUES ('Oral Cavity and Pharynx')
INSERT INTO Cancer VALUES ('Outter Respiratory')
INSERT INTO Cancer VALUES ('Ovary')
INSERT INTO Cancer VALUES ('Pancreas')
INSERT INTO Cancer VALUES ('Prostate')
INSERT INTO Cancer VALUES ('Skin non Melanoma ')
INSERT INTO Cancer VALUES ('Soft Tissue')
INSERT INTO Cancer VALUES ('Stomach')
INSERT INTO Cancer VALUES ('Testis')
INSERT INTO Cancer VALUES ('Thyroid')
INSERT INTO Cancer VALUES ('Trachea')
INSERT INTO Cancer VALUES ('Ureter')
INSERT INTO Cancer VALUES ('Urinary Tract Other')


-- Dar de alta los registros que van en la entidad: 'Ocupacion'

INSERT INTO Ocupacion VALUES ('Busca trabajo')
INSERT INTO Ocupacion VALUES ('Comerciantes, empleados en ventas y agentes de ventas')
INSERT INTO Ocupacion VALUES ('Funcionarios, directores y jefes')
INSERT INTO Ocupacion VALUES ('Insuficientemente especificada')
INSERT INTO Ocupacion VALUES ('No aplica a menores de 5 años')
INSERT INTO Ocupacion VALUES ('No especificada')
INSERT INTO Ocupacion VALUES ('No trabaja')
INSERT INTO Ocupacion VALUES ('Operadores de maquinaria industrial, ensambladores, choferes y conductores de transporte')
INSERT INTO Ocupacion VALUES ('Profesionistas y técnicos')
INSERT INTO Ocupacion VALUES ('Trabajadores artesanales')
INSERT INTO Ocupacion VALUES ('Trabajadores auxiliares en actividades administrativas')
INSERT INTO Ocupacion VALUES ('Trabajadores en actividades agrícolas, ganaderas, forestales, caza y pesca')
INSERT INTO Ocupacion VALUES ('Trabajadores en actividades elementales y de apoyo')
INSERT INTO Ocupacion VALUES ('Trabajadores en servicios personales y vigilancia')


-- Dar de alta los registros que van en la entidad: 'Escolaridad'

INSERT INTO Escolaridad VALUES ('No especificada ')
INSERT INTO Escolaridad VALUES ('No aplica a menores de 3 años')
INSERT INTO Escolaridad VALUES ('Sin escolaridad')
INSERT INTO Escolaridad VALUES ('Preescolar')
INSERT INTO Escolaridad VALUES ('Primaria completa')
INSERT INTO Escolaridad VALUES ('Secundaria incompleta')
INSERT INTO Escolaridad VALUES ('Secundaria completa')
INSERT INTO Escolaridad VALUES ('Bachillerato o preparatoria')
INSERT INTO Escolaridad VALUES ('Profesional')
INSERT INTO Escolaridad VALUES ('Posgrado')
